### ISSUE TITLE
No handler found for the command: 'extension.ftpsyncdownload'

### ISSUE THREAD

**Issue by grvpanchal** [lukasz-wronski/vscode-ftp-sync#1]
I am trying to download but I get this error. Please help!

**Comment by lukasz-wronski** [comment]
Hi @grvpanchal! Thanks for reporting an issue. I've checked it. Technically the problem is that not all commands activates the plugin if there is no configuration file. To run the plugin properly configuration file is needed. 

Solution for you is to run command: __Ftp-sync: Init__ first, then use download command.
This command will generate configuration file for you - fill it with FTP connection details.

If it will help, then I will try to add information messages instead of this nasty error.

**Comment by nasal** [comment]
Hi there, I get the same error even though I have the (configured) ftp-sync.json file inside .vscode. 
Running VS Code 0.10.1 on Windows 10 (1511).

**Comment by lukasz-wronski** [comment]
@nasal - okay, I will try to fix it in tomorrow or day after.

**Comment by nasal** [comment]
@lukasz-wronski: yes, check the screenshot below.

![screen](https://cloud.githubusercontent.com/assets/4168923/11349194/1edd0564-922b-11e5-8094-675a9ae68bfd.png)

**Comment by lukasz-wronski** [comment]
Ok. Thanks, I'll check this out.

**Comment by lukasz-wronski** [comment]
@grvpanchal 
@nasal 

Can you check now? I've published fix.

The problem was that package used in download command was not added to my package.json file (installation without --save option), so it was working fine on debug but was not attached to extension content when published.

**Comment by grvpanchal** [comment]
I had same problem as @nasal screenshot. Do I have to reinstall to get the fix?

**Comment by grvpanchal** [comment]
Its working now!!  Great Extension, Thanks!!

**Comment by lukasz-wronski** [comment]
Thanks for confirmation. Let me know if you'd find any other problems.

**Comment by grvpanchal** [comment]
Currently, I was downloading my project and internet got disconnected while downloading. So when I reconnected, I had to begin the downloading from the start. Can you do an auto reconnect from the point where the downloading stopped?

**Comment by lukasz-wronski** [comment]
I will think of it and add possible solution to a roadmap.
