### ISSUE TITLE
FTP-Sync should not upload ignored files

### ISSUE THREAD

**Issue by rivetchip** [lukasz-wronski/vscode-ftp-sync#105]
Hello,

When doing a sync, like "Local to remote" > "folder **.** " > "Full Sync", ignored files defined in the config file "ftp-sync.json" are still uploaded on server.

For example :
```
"ignore": [
    "\\.vscode",
    "\\.git"
]
```

Everything inside ".vscode" will be uploaded, even the "ftp-sync" config file, which is pretty dangerous.

**Sync summary :**
```
"filesToAdd": [
    ".vscode/ftp-sync.json",
],

...

"dirsToAdd": [
    ".vscode",
],
```

**Comment by Disassembler0** [comment]
Affects me too. Additionally, when I actually upload ".vscode" (or whatever starting with dot), in next round it tries to remove the same name without the dot ("vscode"), which obviously does not exist and fails.

```
{
    "_readMe": "Review list of sync operations, then use Ftp-sync: Commit command to accept changes",
    "_warning": "This file should not be saved, reopened review file won't work!",
    "filesToUpdate": [],
    "filesToAdd": [
        ".vscode/ftp-sync.json"
    ],
    "dirsToAdd": [
        ".vscode"
    ],
    "filesToRemove": [
        "vscode/ftp-sync.json"
    ],
    "dirsToRemove": [
        "vscode"
    ]
}
```

**Comment by kohlerdominik** [comment]
Windows10:

There's still a problem with this...

It work's if you remove the dot in the foldername in front of "\\.vscode" -> "\\vscode" 

But with this change, UploadOnSave doensn't work anymore. i think this should not be a big issue since it worked before. Maybe it has to do with some type of error handling of the config file?
