### ISSUE TITLE
All configured authentication methods failed when using privateKeyPath

### ISSUE THREAD

**Issue by ArvinH** [lukasz-wronski/vscode-ftp-sync#158]
I use this extension for a while, usually, I use password to sftp my remote server which works great. But I keep receiving following error message when I try to use privateKey to upload files: 
**"Ftp-sync: Uploading xxx.jsx failed: Error: All configured authentication methods failed"** 

I can use the same key to sftp my server with sublime-text3 (sftp plugin), so I suppose the key is fine.
Anyone encounter same problem?

vscode: 1.11.2
ftp-sync: 0.3.3
macOS: 10.12.4 (Sierra)

Here is my config:

```js
{
    "remotePath": "/home/arvin/my-app-test",
    "host": "good.test.sg.com",
    "username": "arvin",
    "port": 22,
    "secure": false,
    "protocol": "sftp",
    "uploadOnSave": true,
    "passive": false,
    "debug": true,
    "privateKeyPath": "/Users/arvin/.ssh/id_rsa",
    "passphrase": null,
    "ignore": [
        "\\.vscode",
        "\\.git",
        "\\.DS_Store"
    ],
    "generatedFiles": {
        "uploadOnSave": false,
        "extensionsToInclude": [],
        "path": ""
    }
}
```

**Comment by gdw2** [comment]
Same for me.  Using windows.

**Comment by gdw2** [comment]
It looks like the password defaults to '`password`'.  I tried explicitly setting it to `null`, but still no dice.

https://github.com/lukasz-wronski/vscode-ftp-sync/blob/34075b5d3c4d81176fce55aa39820c9c4e623c85/modules/ftp-config.js#L22

**Comment by gdw2** [comment]
Nope, I was wrong.  I had the wrong username (as evident by my server's ssh log).  Works for me.

**Comment by ArvinH** [comment]
It's good to see you solved your problems!
I double check my username and other wordings still no luck.

maybe I will find time to download the source code then debug it by myself.

**Comment by ArvinH** [comment]
OK, I found the issue.

When I tried to debug on this extension, I found it works fine in Extension Development VS Code instance, and my extension version in vscode is latest ( 0.3.3 ), so I went to `~/.vscode/extensions/lukasz-wronski.ftp-sync-0.3.3/` to see if the "code" is latest, turns out it didn't get the latest code, I'm pretty sure I've re-installed this extension couple times..

however, I update the code in `~/.vscode/extensions/` manually, and it works now.

**Comment by yahilmadakiya** [comment]
I am facing the same issue.

**Comment by timowang1991** [comment]
Let me clarify and elaborate what @ArvinH is trying to say here and how this issue is solved here.

If you are using ssh-agent, your config should have a key-value pair such as 
```
{
    ...
    "agent": "/path/to/agent/file/",
    ...
}
```
However, this will result in an error of `All configured authentication methods failed` because the vscode marketplace does not have the latest version of `ftp-sync` from https://github.com/lukasz-wronski/vscode-ftp-sync 

To solve this issue, use a text editor (e.g. vim) and make changes to the files as what was done in this PR https://github.com/lukasz-wronski/vscode-ftp-sync/pull/134/files manually under the directory `~/.vscode/extensions/lukasz-wronski.ftp-sync-0.3.3/`.

Restart vscode and you are good to go.

**Comment by JackieLam** [comment]
I had exactly the same error message (for several other VSCode plugins as well) and spent the whole afternoon to solve the issue. 
For my case, the incorrect setting turns out to be on the server side. 
My server is SLES 12. 
Solution: 
1. edit /etc/ssh/sshd_config
PasswordAuthentication yes (turn this configuration to "no" and then everything works). 
2. service sshd restart
3. try sftp again and it works.
