### ISSUE TITLE
Pushing changed files with same amount of chars doesn't count as changed

### ISSUE THREAD

**Issue by nuttmeister** [lukasz-wronski/vscode-ftp-sync#61]
Changing sqlQuery1 = "select" to sqlQuery2 = "select" will not count as a changed file when pushing local to remote. Only when you change the number of chars in the files does it work.

So adding a whitespace, comment etc. will trigger it be "changed".

**Comment by Sgamo** [comment]
IMHO, "last modified time" should be the only "parameter" to be compared with remote side (when L2R, ad vice versa), or at least it could be put as an option in ftp-sync.json.

I'll add a request to keep "last modified time" and "creation date" on remote side same as "last modified" on local (when L2R, ad vice versa), because this is the main problem I have with this very useful extention. I'm new with VSCode and node.js, I'll try to have a look in code when I'm not coding for work ;-)

Thanx to author and contributors, anyway!
