### ISSUE TITLE
After some tryes the Review file stopped to work

### ISSUE THREAD

**Issue by lukasz-wronski** [lukasz-wronski/vscode-ftp-sync#7]
After some tryes the Review file stopped to work, it is not been generated anymore, even after I close and reopen VSCode.

Reported by @EthraZa

**Comment by EthraZa** [comment]
Not sure if it is related, but when I try to sync and ask to Review, it just sits there and shows nothing, but I noticed in the botton bar this sentence:
~~~
Ftp-sync: collecting local files list (rpt)
~~~
That sits there forever.

If it is related to collectiong modifed files (or something) on local and is freezing, I was thinking about an alternative to that:

I read on the VSCode GitHub recently, that someone asked the VSCode should have an attacheble event like onBeforeSaveFile so any plugin can intercept when any file is about to be saved an act upon it. I believe you already use it or something like it because you have the uploadOnSave.
For ftp-sync, with uploadOnSave:false, it could be used to register a modified file that is now marked as "dirty" the same way Git does.
If VSCode API lets you add some icon on left bar or botton bar, you could keep it showing the number of files waiting for commit, same way VSCode Git icon does, and can just keep append new files to your transaction json.

**Comment by EthraZa** [comment]
It just crossed my way and I wanted to share with you so you can see if it can be used somehow by Ftp-sync: 
https://github.com/git-ftp/git-ftp

**Comment by lukasz-wronski** [comment]
@EthraZa Can you check if you still have this review problem with 0.2.1?

**Comment by EthraZa** [comment]
I updated and it didn't work.
So I opened a terminal (I'm on Ubuntu Linux 15.04), cd to project folder and called it as **/opt/VSCode/Code**. Now the Review worked. 
I closed VSCode and called it again from the docked icon on my Desktop bar, it didn't work again. 
It seems to me as some path issue.

---
As a second note:
Even calling it from the project folder so the Review works, when I call Commit it gives the following error:
~~~
[Error] Ftp-sync: sync error: Error: Can't open that file: No such file or directory
~~~
Seems related to path as well.

**Comment by RafaMedina** [comment]
+1

**Comment by lukasz-wronski** [comment]
@EthraZa I'm not creating this file nowhere. It's just an editor window with this json, it's not saved on disk. It's like you create new file but do not save it yet.

Can you check if those problem still exists in `0.2.6`. I'm having trouble with reproducing it?

**Comment by EthraZa** [comment]
It still open only if I go to the project folder in a terminal and call Code from there.

If I open VSCode from an icon on my desktop, the Review does not work. Even if I go to the menu File->Open Folder it still dosn't work.

So, we can say the Review is working, it is just when I open VSCode from an Desktop icon that something goes wrong and it fails. I would guess it is path related, but I can't be sure.
There is some way to me to debug it?

**Comment by lukasz-wronski** [comment]
Should work fine in `0.2.9`
